[2023-04-11T17:15:03.097+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T17:04:00+00:00 [queued]>
[2023-04-11T17:15:03.106+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T17:04:00+00:00 [queued]>
[2023-04-11T17:15:03.107+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:15:03.107+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 4
[2023-04-11T17:15:03.108+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T17:15:03.123+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 17:04:00+00:00
[2023-04-11T17:15:03.128+0000] {standard_task_runner.py:55} INFO - Started process 6631 to run task
[2023-04-11T17:15:03.130+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T17:04:00+00:00', '--job-id', '759', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp_csg3jw2']
[2023-04-11T17:15:03.131+0000] {standard_task_runner.py:83} INFO - Job 759: Subtask id_2
[2023-04-11T17:15:03.192+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T17:04:00+00:00 [running]> on host b518195edd5e
[2023-04-11T17:15:03.254+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T17:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T17:04:00+00:00
[2023-04-11T17:15:03.255+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T17:15:03.256+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T17:15:03.264+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T17:15:03.349+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py': [Errno 5] Input/output error
[2023-04-11T17:15:03.351+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-11T17:15:03.360+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-11T17:15:03.363+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T170400, start_date=20230411T171503, end_date=20230411T171503
[2023-04-11T17:15:03.375+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 759 for task id_2 (Bash command failed. The command returned a non-zero exit code 2.; 6631)
[2023-04-11T17:15:03.382+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T17:15:03.399+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
