[2023-04-14T15:08:02.550+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T15:07:00+00:00 [queued]>
[2023-04-14T15:08:02.558+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T15:07:00+00:00 [queued]>
[2023-04-14T15:08:02.558+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T15:08:02.559+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 4
[2023-04-14T15:08:02.559+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T15:08:02.572+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-14 15:07:00+00:00
[2023-04-14T15:08:02.577+0000] {standard_task_runner.py:55} INFO - Started process 2630 to run task
[2023-04-14T15:08:02.579+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-14T15:07:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmplb288py_']
[2023-04-14T15:08:02.580+0000] {standard_task_runner.py:83} INFO - Job 146: Subtask id_2
[2023-04-14T15:08:02.627+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T15:07:00+00:00 [running]> on host 6f8cd9778af0
[2023-04-14T15:08:02.690+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T15:07:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T15:07:00+00:00
[2023-04-14T15:08:02.691+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T15:08:02.692+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-14T15:08:02.701+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T15:08:04.558+0000] {subprocess.py:93} INFO - 
[2023-04-14T15:08:04.559+0000] {subprocess.py:93} INFO - --DEBUG: __file__:     /opt/***/src/news_comments_crawlers/crawlers/config/Constants.py
[2023-04-14T15:08:04.559+0000] {subprocess.py:93} INFO - 
[2023-04-14T15:08:04.560+0000] {subprocess.py:93} INFO - -- Session Object : Good to go.
[2023-04-14T15:08:04.560+0000] {subprocess.py:93} INFO - 
[2023-04-14T15:08:04.561+0000] {subprocess.py:93} INFO - -- Folders: Good to go.
[2023-04-14T15:08:04.561+0000] {subprocess.py:93} INFO - []
[2023-04-14T15:08:04.563+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-14T15:08:04.564+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 10, in <module>
[2023-04-14T15:08:04.564+0000] {subprocess.py:93} INFO -     from Functions import *
[2023-04-14T15:08:04.565+0000] {subprocess.py:93} INFO -   File "<fstring>", line 1
[2023-04-14T15:08:04.565+0000] {subprocess.py:93} INFO -     (USE_CACHE=)
[2023-04-14T15:08:04.565+0000] {subprocess.py:93} INFO -               ^
[2023-04-14T15:08:04.566+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-04-14T15:08:04.718+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-14T15:08:04.733+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-14T15:08:04.738+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230414T150700, start_date=20230414T150802, end_date=20230414T150804
[2023-04-14T15:08:04.755+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 146 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 2630)
[2023-04-14T15:08:04.797+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T15:08:04.816+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
