[2023-04-11T13:39:05.691+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:23:00+00:00 [queued]>
[2023-04-11T13:39:05.711+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:23:00+00:00 [queued]>
[2023-04-11T13:39:05.711+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T13:39:05.712+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-11T13:39:05.712+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T13:39:05.734+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 13:23:00+00:00
[2023-04-11T13:39:05.739+0000] {standard_task_runner.py:55} INFO - Started process 1235 to run task
[2023-04-11T13:39:05.741+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T13:23:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmphfao3s54']
[2023-04-11T13:39:05.743+0000] {standard_task_runner.py:83} INFO - Job 106: Subtask id_2
[2023-04-11T13:39:05.806+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T13:23:00+00:00 [running]> on host b518195edd5e
[2023-04-11T13:39:05.884+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T13:23:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T13:23:00+00:00
[2023-04-11T13:39:05.886+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T13:39:05.888+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T13:39:05.904+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T13:39:06.013+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py': [Errno 5] Input/output error
[2023-04-11T13:39:06.031+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-11T13:39:06.042+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-11T13:39:06.047+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T132300, start_date=20230411T133905, end_date=20230411T133906
[2023-04-11T13:39:06.062+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 106 for task id_2 (Bash command failed. The command returned a non-zero exit code 2.; 1235)
[2023-04-11T13:39:06.075+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T13:39:06.098+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
