[2023-04-12T13:39:02.114+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T13:38:00+00:00 [queued]>
[2023-04-12T13:39:02.121+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T13:38:00+00:00 [queued]>
[2023-04-12T13:39:02.122+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T13:39:02.122+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 4
[2023-04-12T13:39:02.122+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T13:39:02.136+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-12 13:38:00+00:00
[2023-04-12T13:39:02.139+0000] {standard_task_runner.py:55} INFO - Started process 12408 to run task
[2023-04-12T13:39:02.141+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-12T13:38:00+00:00', '--job-id', '6883', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpv5i7dg49']
[2023-04-12T13:39:02.142+0000] {standard_task_runner.py:83} INFO - Job 6883: Subtask id_2
[2023-04-12T13:39:02.189+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T13:38:00+00:00 [running]> on host b518195edd5e
[2023-04-12T13:39:02.247+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T13:38:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-12T13:38:00+00:00
[2023-04-12T13:39:02.249+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T13:39:02.250+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-12T13:39:02.256+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T13:39:02.425+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T13:39:02.426+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-12T13:39:02.426+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-12T13:39:02.426+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-12T13:39:02.427+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-12T13:39:02.427+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-12T13:39:02.428+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T13:39:02.437+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T13:39:02.441+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230412T133800, start_date=20230412T133902, end_date=20230412T133902
[2023-04-12T13:39:02.452+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6883 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 12408)
[2023-04-12T13:39:02.474+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T13:39:02.488+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
