[2023-04-14T14:51:43.931+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:33:00+00:00 [queued]>
[2023-04-14T14:51:43.952+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:33:00+00:00 [queued]>
[2023-04-14T14:51:43.953+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:51:43.954+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-14T14:51:43.959+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:51:43.996+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-14 14:33:00+00:00
[2023-04-14T14:51:44.006+0000] {standard_task_runner.py:55} INFO - Started process 705 to run task
[2023-04-14T14:51:44.017+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-14T14:33:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpxc5bl138']
[2023-04-14T14:51:44.022+0000] {standard_task_runner.py:83} INFO - Job 58: Subtask id_2
[2023-04-14T14:51:44.148+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:33:00+00:00 [running]> on host 6f8cd9778af0
[2023-04-14T14:51:44.315+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:33:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T14:33:00+00:00
[2023-04-14T14:51:44.317+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T14:51:44.320+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-14T14:51:44.347+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T14:51:48.898+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.900+0000] {subprocess.py:93} INFO - --DEBUG: getcwd:       /tmp/***tmpsca0vqqx
[2023-04-14T14:51:48.902+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.905+0000] {subprocess.py:93} INFO - --DEBUG: __file__:     /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py
[2023-04-14T14:51:48.907+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.909+0000] {subprocess.py:93} INFO - -- Session Object : Good to go.
[2023-04-14T14:51:48.911+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.912+0000] {subprocess.py:93} INFO - -- Log Folder: Failed to create.
[2023-04-14T14:51:48.913+0000] {subprocess.py:93} INFO - [Errno 2] No such file or directory: '/opt/***/src/news_comments_crawlers/crawlers/out/2023-04-14'
[2023-04-14T14:51:48.914+0000] {subprocess.py:93} INFO - []
[2023-04-14T14:51:48.917+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-14T14:51:48.918+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 13, in <module>
[2023-04-14T14:51:48.919+0000] {subprocess.py:93} INFO -     from Functions import *
[2023-04-14T14:51:48.920+0000] {subprocess.py:93} INFO -   File "<fstring>", line 1
[2023-04-14T14:51:48.921+0000] {subprocess.py:93} INFO -     (USE_CACHE=)
[2023-04-14T14:51:48.922+0000] {subprocess.py:93} INFO -               ^
[2023-04-14T14:51:48.923+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-04-14T14:51:49.536+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-14T14:51:49.565+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-14T14:51:49.572+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230414T143300, start_date=20230414T145143, end_date=20230414T145149
[2023-04-14T14:51:49.603+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 58 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 705)
[2023-04-14T14:51:49.630+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T14:51:49.662+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
