[2023-04-12T14:42:03.092+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T14:36:00+00:00 [queued]>
[2023-04-12T14:42:03.101+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T14:36:00+00:00 [queued]>
[2023-04-12T14:42:03.102+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T14:42:03.102+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-12T14:42:03.103+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T14:42:03.118+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-12 14:36:00+00:00
[2023-04-12T14:42:03.123+0000] {standard_task_runner.py:55} INFO - Started process 14876 to run task
[2023-04-12T14:42:03.127+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-12T14:36:00+00:00', '--job-id', '7200', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmphdj6zvmi']
[2023-04-12T14:42:03.129+0000] {standard_task_runner.py:83} INFO - Job 7200: Subtask id_2
[2023-04-12T14:42:03.180+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T14:36:00+00:00 [running]> on host b518195edd5e
[2023-04-12T14:42:03.238+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T14:36:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-12T14:36:00+00:00
[2023-04-12T14:42:03.240+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T14:42:03.241+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-12T14:42:03.248+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T14:42:03.372+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T14:42:03.373+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-12T14:42:03.373+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-12T14:42:03.374+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-12T14:42:03.374+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-12T14:42:03.375+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-12T14:42:03.376+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T14:42:03.386+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T14:42:03.390+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230412T143600, start_date=20230412T144203, end_date=20230412T144203
[2023-04-12T14:42:03.402+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7200 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 14876)
[2023-04-12T14:42:03.419+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T14:42:03.433+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
