[2023-04-14T14:51:44.024+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 manual__2023-04-14T14:45:14.857096+00:00 [queued]>
[2023-04-14T14:51:44.048+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 manual__2023-04-14T14:45:14.857096+00:00 [queued]>
[2023-04-14T14:51:44.049+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:51:44.051+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-14T14:51:44.052+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:51:44.083+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-14 14:45:14.857096+00:00
[2023-04-14T14:51:44.096+0000] {standard_task_runner.py:55} INFO - Started process 712 to run task
[2023-04-14T14:51:44.100+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'manual__2023-04-14T14:45:14.857096+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp0rrj1hb_']
[2023-04-14T14:51:44.109+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask id_2
[2023-04-14T14:51:44.249+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 manual__2023-04-14T14:45:14.857096+00:00 [running]> on host 6f8cd9778af0
[2023-04-14T14:51:44.436+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:45:14.857096+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-14T14:45:14.857096+00:00
[2023-04-14T14:51:44.440+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T14:51:44.446+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-14T14:51:44.475+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T14:51:48.852+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.855+0000] {subprocess.py:93} INFO - --DEBUG: getcwd:       /tmp/***tmpaqat7sjk
[2023-04-14T14:51:48.857+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.859+0000] {subprocess.py:93} INFO - --DEBUG: __file__:     /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py
[2023-04-14T14:51:48.861+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.862+0000] {subprocess.py:93} INFO - -- Session Object : Good to go.
[2023-04-14T14:51:48.863+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.865+0000] {subprocess.py:93} INFO - -- Log Folder: Failed to create.
[2023-04-14T14:51:48.867+0000] {subprocess.py:93} INFO - [Errno 2] No such file or directory: '/opt/***/src/news_comments_crawlers/crawlers/out/2023-04-14'
[2023-04-14T14:51:48.868+0000] {subprocess.py:93} INFO - []
[2023-04-14T14:51:48.869+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-14T14:51:48.871+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 13, in <module>
[2023-04-14T14:51:48.873+0000] {subprocess.py:93} INFO -     from Functions import *
[2023-04-14T14:51:48.874+0000] {subprocess.py:93} INFO -   File "<fstring>", line 1
[2023-04-14T14:51:48.875+0000] {subprocess.py:93} INFO -     (USE_CACHE=)
[2023-04-14T14:51:48.876+0000] {subprocess.py:93} INFO -               ^
[2023-04-14T14:51:48.877+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-04-14T14:51:49.499+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-14T14:51:49.532+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-14T14:51:49.544+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230414T144514, start_date=20230414T145144, end_date=20230414T145149
[2023-04-14T14:51:49.578+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 70 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 712)
[2023-04-14T14:51:49.615+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T14:51:49.647+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
