[2023-04-12T12:25:02.414+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T12:19:00+00:00 [queued]>
[2023-04-12T12:25:02.423+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T12:19:00+00:00 [queued]>
[2023-04-12T12:25:02.424+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T12:25:02.425+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-12T12:25:02.425+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T12:25:02.440+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-12 12:19:00+00:00
[2023-04-12T12:25:02.444+0000] {standard_task_runner.py:55} INFO - Started process 9519 to run task
[2023-04-12T12:25:02.446+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-12T12:19:00+00:00', '--job-id', '6514', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpjr9_vh_o']
[2023-04-12T12:25:02.447+0000] {standard_task_runner.py:83} INFO - Job 6514: Subtask id_2
[2023-04-12T12:25:02.497+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T12:19:00+00:00 [running]> on host b518195edd5e
[2023-04-12T12:25:02.561+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T12:19:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-12T12:19:00+00:00
[2023-04-12T12:25:02.562+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T12:25:02.563+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-12T12:25:02.575+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T12:25:02.718+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T12:25:02.719+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-12T12:25:02.719+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-12T12:25:02.719+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-12T12:25:02.720+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-12T12:25:02.720+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-12T12:25:02.722+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T12:25:02.731+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T12:25:02.734+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230412T121900, start_date=20230412T122502, end_date=20230412T122502
[2023-04-12T12:25:02.747+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6514 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 9519)
[2023-04-12T12:25:02.779+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T12:25:02.793+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
