[2023-04-12T22:30:03.051+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T22:24:00+00:00 [queued]>
[2023-04-12T22:30:03.059+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T22:24:00+00:00 [queued]>
[2023-04-12T22:30:03.060+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T22:30:03.061+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-12T22:30:03.061+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T22:30:03.076+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-12 22:24:00+00:00
[2023-04-12T22:30:03.079+0000] {standard_task_runner.py:55} INFO - Started process 632 to run task
[2023-04-12T22:30:03.081+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-12T22:24:00+00:00', '--job-id', '9540', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmptdpqyr8s']
[2023-04-12T22:30:03.082+0000] {standard_task_runner.py:83} INFO - Job 9540: Subtask id_2
[2023-04-12T22:30:03.129+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T22:24:00+00:00 [running]> on host b518195edd5e
[2023-04-12T22:30:03.184+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T22:24:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-12T22:24:00+00:00
[2023-04-12T22:30:03.185+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T22:30:03.186+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-12T22:30:03.192+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T22:30:03.326+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T22:30:03.327+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-12T22:30:03.327+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-12T22:30:03.327+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-12T22:30:03.328+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-12T22:30:03.328+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-12T22:30:03.330+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T22:30:03.338+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T22:30:03.341+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230412T222400, start_date=20230412T223003, end_date=20230412T223003
[2023-04-12T22:30:03.353+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9540 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 632)
[2023-04-12T22:30:03.373+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T22:30:03.387+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
