[2023-04-13T02:36:04.390+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T02:20:00+00:00 [queued]>
[2023-04-13T02:36:04.398+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T02:20:00+00:00 [queued]>
[2023-04-13T02:36:04.399+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T02:36:04.399+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-13T02:36:04.400+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T02:36:04.415+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-13 02:20:00+00:00
[2023-04-13T02:36:04.418+0000] {standard_task_runner.py:55} INFO - Started process 10221 to run task
[2023-04-13T02:36:04.420+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-13T02:20:00+00:00', '--job-id', '10771', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpfysss1dg']
[2023-04-13T02:36:04.422+0000] {standard_task_runner.py:83} INFO - Job 10771: Subtask id_2
[2023-04-13T02:36:04.468+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T02:20:00+00:00 [running]> on host b518195edd5e
[2023-04-13T02:36:04.530+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T02:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-13T02:20:00+00:00
[2023-04-13T02:36:04.532+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-13T02:36:04.532+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-13T02:36:04.537+0000] {subprocess.py:86} INFO - Output:
[2023-04-13T02:36:04.665+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-13T02:36:04.665+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-13T02:36:04.666+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-13T02:36:04.666+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-13T02:36:04.667+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-13T02:36:04.667+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-13T02:36:04.669+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-13T02:36:04.678+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-13T02:36:04.681+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230413T022000, start_date=20230413T023604, end_date=20230413T023604
[2023-04-13T02:36:04.692+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10771 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 10221)
[2023-04-13T02:36:04.712+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T02:36:04.727+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
