[2023-04-14T14:51:43.932+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:39:00+00:00 [queued]>
[2023-04-14T14:51:43.955+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:39:00+00:00 [queued]>
[2023-04-14T14:51:43.957+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:51:43.959+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 4
[2023-04-14T14:51:43.960+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:51:43.996+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-14 14:39:00+00:00
[2023-04-14T14:51:44.006+0000] {standard_task_runner.py:55} INFO - Started process 706 to run task
[2023-04-14T14:51:44.013+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-14T14:39:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpcse7h085']
[2023-04-14T14:51:44.017+0000] {standard_task_runner.py:83} INFO - Job 57: Subtask id_2
[2023-04-14T14:51:44.150+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-14T14:39:00+00:00 [running]> on host 6f8cd9778af0
[2023-04-14T14:51:44.325+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:39:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T14:39:00+00:00
[2023-04-14T14:51:44.329+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T14:51:44.333+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-14T14:51:44.359+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T14:51:48.799+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.800+0000] {subprocess.py:93} INFO - --DEBUG: getcwd:       /tmp/***tmpi_rw4ome
[2023-04-14T14:51:48.802+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.803+0000] {subprocess.py:93} INFO - --DEBUG: __file__:     /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py
[2023-04-14T14:51:48.805+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.807+0000] {subprocess.py:93} INFO - -- Session Object : Good to go.
[2023-04-14T14:51:48.808+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:51:48.810+0000] {subprocess.py:93} INFO - -- Log Folder: Failed to create.
[2023-04-14T14:51:48.812+0000] {subprocess.py:93} INFO - [Errno 2] No such file or directory: '/opt/***/src/news_comments_crawlers/crawlers/out/2023-04-14'
[2023-04-14T14:51:48.814+0000] {subprocess.py:93} INFO - []
[2023-04-14T14:51:48.816+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-14T14:51:48.817+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 13, in <module>
[2023-04-14T14:51:48.819+0000] {subprocess.py:93} INFO -     from Functions import *
[2023-04-14T14:51:48.820+0000] {subprocess.py:93} INFO -   File "<fstring>", line 1
[2023-04-14T14:51:48.821+0000] {subprocess.py:93} INFO -     (USE_CACHE=)
[2023-04-14T14:51:48.822+0000] {subprocess.py:93} INFO -               ^
[2023-04-14T14:51:48.823+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-04-14T14:51:49.447+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-14T14:51:49.483+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-14T14:51:49.500+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230414T143900, start_date=20230414T145143, end_date=20230414T145149
[2023-04-14T14:51:49.551+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 57 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 706)
[2023-04-14T14:51:49.588+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T14:51:49.624+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
