[2023-04-12T08:53:02.736+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T08:47:00+00:00 [queued]>
[2023-04-12T08:53:02.744+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T08:47:00+00:00 [queued]>
[2023-04-12T08:53:02.745+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T08:53:02.745+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-12T08:53:02.745+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T08:53:02.759+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-12 08:47:00+00:00
[2023-04-12T08:53:02.763+0000] {standard_task_runner.py:55} INFO - Started process 1264 to run task
[2023-04-12T08:53:02.765+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-12T08:47:00+00:00', '--job-id', '5454', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp1ae_fdwm']
[2023-04-12T08:53:02.766+0000] {standard_task_runner.py:83} INFO - Job 5454: Subtask id_2
[2023-04-12T08:53:02.810+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-12T08:47:00+00:00 [running]> on host b518195edd5e
[2023-04-12T08:53:02.865+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-12T08:47:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-12T08:47:00+00:00
[2023-04-12T08:53:02.866+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-12T08:53:02.867+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-12T08:53:02.874+0000] {subprocess.py:86} INFO - Output:
[2023-04-12T08:53:03.037+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-12T08:53:03.037+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-12T08:53:03.038+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-12T08:53:03.038+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-12T08:53:03.038+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-12T08:53:03.039+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-12T08:53:03.040+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-12T08:53:03.049+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-12T08:53:03.052+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230412T084700, start_date=20230412T085302, end_date=20230412T085303
[2023-04-12T08:53:03.062+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5454 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 1264)
[2023-04-12T08:53:03.098+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-12T08:53:03.112+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
