[2023-04-13T00:21:04.792+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T00:05:00+00:00 [queued]>
[2023-04-13T00:21:04.800+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T00:05:00+00:00 [queued]>
[2023-04-13T00:21:04.801+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T00:21:04.802+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-13T00:21:04.802+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T00:21:04.816+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-13 00:05:00+00:00
[2023-04-13T00:21:04.820+0000] {standard_task_runner.py:55} INFO - Started process 4965 to run task
[2023-04-13T00:21:04.822+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-13T00:05:00+00:00', '--job-id', '10096', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp0tv5ppao']
[2023-04-13T00:21:04.823+0000] {standard_task_runner.py:83} INFO - Job 10096: Subtask id_2
[2023-04-13T00:21:04.868+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T00:05:00+00:00 [running]> on host b518195edd5e
[2023-04-13T00:21:04.924+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T00:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-13T00:05:00+00:00
[2023-04-13T00:21:04.925+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-13T00:21:04.926+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-13T00:21:04.932+0000] {subprocess.py:86} INFO - Output:
[2023-04-13T00:21:05.094+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-13T00:21:05.095+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-13T00:21:05.095+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-13T00:21:05.095+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-13T00:21:05.096+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-13T00:21:05.096+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-13T00:21:05.097+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-13T00:21:05.106+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-13T00:21:05.109+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230413T000500, start_date=20230413T002104, end_date=20230413T002105
[2023-04-13T00:21:05.120+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10096 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 4965)
[2023-04-13T00:21:05.155+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T00:21:05.170+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
