[2023-04-11T18:20:04.259+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T18:04:00+00:00 [queued]>
[2023-04-11T18:20:04.267+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T18:04:00+00:00 [queued]>
[2023-04-11T18:20:04.268+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T18:20:04.269+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-11T18:20:04.269+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T18:20:04.283+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 18:04:00+00:00
[2023-04-11T18:20:04.287+0000] {standard_task_runner.py:55} INFO - Started process 9170 to run task
[2023-04-11T18:20:04.289+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T18:04:00+00:00', '--job-id', '1085', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpk_r81w2w']
[2023-04-11T18:20:04.291+0000] {standard_task_runner.py:83} INFO - Job 1085: Subtask id_2
[2023-04-11T18:20:04.344+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T18:04:00+00:00 [running]> on host b518195edd5e
[2023-04-11T18:20:04.403+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T18:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T18:04:00+00:00
[2023-04-11T18:20:04.405+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T18:20:04.406+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T18:20:04.415+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T18:20:04.495+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py': [Errno 5] Input/output error
[2023-04-11T18:20:04.499+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-11T18:20:04.508+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-11T18:20:04.511+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T180400, start_date=20230411T182004, end_date=20230411T182004
[2023-04-11T18:20:04.521+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1085 for task id_2 (Bash command failed. The command returned a non-zero exit code 2.; 9170)
[2023-04-11T18:20:04.542+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T18:20:04.588+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
