[2023-04-11T15:15:09.594+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T15:04:00+00:00 [queued]>
[2023-04-11T15:15:09.602+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T15:04:00+00:00 [queued]>
[2023-04-11T15:15:09.603+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T15:15:09.604+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 4
[2023-04-11T15:15:09.604+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T15:15:09.617+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 15:04:00+00:00
[2023-04-11T15:15:09.622+0000] {standard_task_runner.py:55} INFO - Started process 3129 to run task
[2023-04-11T15:15:09.623+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T15:04:00+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp_cmsi9pz']
[2023-04-11T15:15:09.625+0000] {standard_task_runner.py:83} INFO - Job 330: Subtask id_2
[2023-04-11T15:15:09.676+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T15:04:00+00:00 [running]> on host b518195edd5e
[2023-04-11T15:15:09.737+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T15:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T15:04:00+00:00
[2023-04-11T15:15:09.738+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T15:15:09.739+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T15:15:09.748+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T15:15:09.837+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py': [Errno 5] Input/output error
[2023-04-11T15:15:09.839+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-11T15:15:09.849+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-11T15:15:09.852+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T150400, start_date=20230411T151509, end_date=20230411T151509
[2023-04-11T15:15:09.862+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 330 for task id_2 (Bash command failed. The command returned a non-zero exit code 2.; 3129)
[2023-04-11T15:15:09.876+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T15:15:09.891+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
