[2023-04-11T23:25:01.866+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T23:24:00+00:00 [queued]>
[2023-04-11T23:25:01.875+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T23:24:00+00:00 [queued]>
[2023-04-11T23:25:01.876+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T23:25:01.877+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 4
[2023-04-11T23:25:01.877+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T23:25:01.893+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 23:24:00+00:00
[2023-04-11T23:25:01.964+0000] {standard_task_runner.py:55} INFO - Started process 11589 to run task
[2023-04-11T23:25:01.966+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T23:24:00+00:00', '--job-id', '2613', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpz6g6n1lp']
[2023-04-11T23:25:01.968+0000] {standard_task_runner.py:83} INFO - Job 2613: Subtask id_2
[2023-04-11T23:25:02.021+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T23:24:00+00:00 [running]> on host b518195edd5e
[2023-04-11T23:25:02.078+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T23:24:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T23:24:00+00:00
[2023-04-11T23:25:02.080+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T23:25:02.080+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T23:25:02.087+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T23:25:02.218+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-11T23:25:02.218+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-11T23:25:02.219+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-11T23:25:02.219+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-11T23:25:02.220+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-11T23:25:02.220+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-11T23:25:02.221+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-11T23:25:02.231+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-11T23:25:02.234+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T232400, start_date=20230411T232501, end_date=20230411T232502
[2023-04-11T23:25:02.247+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 2613 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 11589)
[2023-04-11T23:25:02.259+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T23:25:02.273+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
