[2023-04-13T03:21:03.888+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T03:05:00+00:00 [queued]>
[2023-04-13T03:21:03.897+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T03:05:00+00:00 [queued]>
[2023-04-13T03:21:03.897+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T03:21:03.898+0000] {taskinstance.py:1283} INFO - Starting attempt 4 of 4
[2023-04-13T03:21:03.898+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T03:21:03.913+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-13 03:05:00+00:00
[2023-04-13T03:21:03.917+0000] {standard_task_runner.py:55} INFO - Started process 11982 to run task
[2023-04-13T03:21:03.920+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-13T03:05:00+00:00', '--job-id', '10995', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpfsf5e5z7']
[2023-04-13T03:21:03.921+0000] {standard_task_runner.py:83} INFO - Job 10995: Subtask id_2
[2023-04-13T03:21:03.970+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-13T03:05:00+00:00 [running]> on host b518195edd5e
[2023-04-13T03:21:04.027+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T03:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-13T03:05:00+00:00
[2023-04-13T03:21:04.028+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-13T03:21:04.029+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-13T03:21:04.035+0000] {subprocess.py:86} INFO - Output:
[2023-04-13T03:21:04.170+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-13T03:21:04.170+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-13T03:21:04.171+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-13T03:21:04.171+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-13T03:21:04.171+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-13T03:21:04.172+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-13T03:21:04.173+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-13T03:21:04.181+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-13T03:21:04.185+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230413T030500, start_date=20230413T032103, end_date=20230413T032104
[2023-04-13T03:21:04.194+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10995 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 11982)
[2023-04-13T03:21:04.212+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-13T03:21:04.226+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
