[2023-04-09T16:06:01.512+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exe_web_crawlers_dag_v2.id_2 scheduled__2023-04-09T16:05:00+00:00 [queued]>
[2023-04-09T16:06:01.521+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exe_web_crawlers_dag_v2.id_2 scheduled__2023-04-09T16:05:00+00:00 [queued]>
[2023-04-09T16:06:01.521+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T16:06:01.522+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 4
[2023-04-09T16:06:01.522+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T16:06:01.534+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-09 16:05:00+00:00
[2023-04-09T16:06:01.539+0000] {standard_task_runner.py:55} INFO - Started process 2128 to run task
[2023-04-09T16:06:01.541+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exe_web_crawlers_dag_v2', 'id_2', 'scheduled__2023-04-09T16:05:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp_1dr7zix']
[2023-04-09T16:06:01.543+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask id_2
[2023-04-09T16:06:01.597+0000] {task_command.py:388} INFO - Running <TaskInstance: exe_web_crawlers_dag_v2.id_2 scheduled__2023-04-09T16:05:00+00:00 [running]> on host e8e20c2f7d98
[2023-04-09T16:06:01.657+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=exe_web_crawlers_dag_v2
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-09T16:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-09T16:05:00+00:00
[2023-04-09T16:06:01.658+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-09T16:06:01.659+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd pwd']
[2023-04-09T16:06:01.666+0000] {subprocess.py:86} INFO - Output:
[2023-04-09T16:06:01.667+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: pwd: No such file or directory
[2023-04-09T16:06:01.668+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-09T16:06:01.677+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-09T16:06:01.680+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=exe_web_crawlers_dag_v2, task_id=id_2, execution_date=20230409T160500, start_date=20230409T160601, end_date=20230409T160601
[2023-04-09T16:06:01.691+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 104 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 2128)
[2023-04-09T16:06:01.714+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-09T16:06:01.729+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
