[2023-04-11T20:23:01.703+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T20:22:00+00:00 [queued]>
[2023-04-11T20:23:01.712+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T20:22:00+00:00 [queued]>
[2023-04-11T20:23:01.712+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T20:23:01.713+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 4
[2023-04-11T20:23:01.713+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T20:23:01.727+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 20:22:00+00:00
[2023-04-11T20:23:01.730+0000] {standard_task_runner.py:55} INFO - Started process 4503 to run task
[2023-04-11T20:23:01.732+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T20:22:00+00:00', '--job-id', '1703', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmp5xw78h9x']
[2023-04-11T20:23:01.733+0000] {standard_task_runner.py:83} INFO - Job 1703: Subtask id_2
[2023-04-11T20:23:01.779+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T20:22:00+00:00 [running]> on host b518195edd5e
[2023-04-11T20:23:01.836+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T20:22:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T20:22:00+00:00
[2023-04-11T20:23:01.837+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T20:23:01.837+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T20:23:01.843+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T20:23:02.008+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-11T20:23:02.009+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 8, in <module>
[2023-04-11T20:23:02.009+0000] {subprocess.py:93} INFO -     from config.Preprocessor import Preprocessor
[2023-04-11T20:23:02.010+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/config/Preprocessor.py", line 11, in <module>
[2023-04-11T20:23:02.010+0000] {subprocess.py:93} INFO -     from nltk.stem import WordNetLemmatizer
[2023-04-11T20:23:02.010+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'nltk'
[2023-04-11T20:23:02.012+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-11T20:23:02.020+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-11T20:23:02.023+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T202200, start_date=20230411T202301, end_date=20230411T202302
[2023-04-11T20:23:02.034+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1703 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 4503)
[2023-04-11T20:23:02.065+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T20:23:02.079+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
