[2023-04-14T14:45:15.989+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 manual__2023-04-14T14:34:54.983993+00:00 [queued]>
[2023-04-14T14:45:16.012+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 manual__2023-04-14T14:34:54.983993+00:00 [queued]>
[2023-04-14T14:45:16.015+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:45:16.016+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 4
[2023-04-14T14:45:16.017+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T14:45:16.119+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-14 14:34:54.983993+00:00
[2023-04-14T14:45:16.136+0000] {standard_task_runner.py:55} INFO - Started process 215 to run task
[2023-04-14T14:45:16.143+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'manual__2023-04-14T14:34:54.983993+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmppjc4qxfo']
[2023-04-14T14:45:16.147+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask id_2
[2023-04-14T14:45:16.287+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 manual__2023-04-14T14:34:54.983993+00:00 [running]> on host 6f8cd9778af0
[2023-04-14T14:45:16.432+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T14:34:54.983993+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-14T14:34:54.983993+00:00
[2023-04-14T14:45:16.435+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T14:45:16.437+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-14T14:45:16.460+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T14:45:19.729+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:45:19.731+0000] {subprocess.py:93} INFO - -- Session Object : Good to go.
[2023-04-14T14:45:19.732+0000] {subprocess.py:93} INFO - 
[2023-04-14T14:45:19.734+0000] {subprocess.py:93} INFO - -- Log Folder: Failed to create.
[2023-04-14T14:45:19.736+0000] {subprocess.py:93} INFO - [Errno 2] No such file or directory: './src/news_comments_crawlers/crawlers/out/2023-04-14'
[2023-04-14T14:45:19.737+0000] {subprocess.py:93} INFO - []
[2023-04-14T14:45:19.738+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-04-14T14:45:19.740+0000] {subprocess.py:93} INFO -   File "/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py", line 10, in <module>
[2023-04-14T14:45:19.741+0000] {subprocess.py:93} INFO -     from Functions import *
[2023-04-14T14:45:19.742+0000] {subprocess.py:93} INFO -   File "<fstring>", line 1
[2023-04-14T14:45:19.743+0000] {subprocess.py:93} INFO -     (USE_CACHE=)
[2023-04-14T14:45:19.745+0000] {subprocess.py:93} INFO -               ^
[2023-04-14T14:45:19.747+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2023-04-14T14:45:20.199+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-14T14:45:20.214+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-14T14:45:20.219+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230414T143454, start_date=20230414T144515, end_date=20230414T144520
[2023-04-14T14:45:20.240+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 41 for task id_2 (Bash command failed. The command returned a non-zero exit code 1.; 215)
[2023-04-14T14:45:20.258+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T14:45:20.279+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
