[2023-04-11T16:51:03.407+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T16:45:00+00:00 [queued]>
[2023-04-11T16:51:03.415+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T16:45:00+00:00 [queued]>
[2023-04-11T16:51:03.416+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T16:51:03.417+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 4
[2023-04-11T16:51:03.418+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-11T16:51:03.431+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): id_2> on 2023-04-11 16:45:00+00:00
[2023-04-11T16:51:03.436+0000] {standard_task_runner.py:55} INFO - Started process 5691 to run task
[2023-04-11T16:51:03.438+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'execute_24hr_data_scrape', 'id_2', 'scheduled__2023-04-11T16:45:00+00:00', '--job-id', '640', '--raw', '--subdir', 'DAGS_FOLDER/exec_web_crawlers_dag.py', '--cfg-path', '/tmp/tmpq9ei68t4']
[2023-04-11T16:51:03.439+0000] {standard_task_runner.py:83} INFO - Job 640: Subtask id_2
[2023-04-11T16:51:03.491+0000] {task_command.py:388} INFO - Running <TaskInstance: execute_24hr_data_scrape.id_2 scheduled__2023-04-11T16:45:00+00:00 [running]> on host b518195edd5e
[2023-04-11T16:51:03.547+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=xiaochen
AIRFLOW_CTX_DAG_ID=execute_24hr_data_scrape
AIRFLOW_CTX_TASK_ID=id_2
AIRFLOW_CTX_EXECUTION_DATE=2023-04-11T16:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-11T16:45:00+00:00
[2023-04-11T16:51:03.548+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-11T16:51:03.549+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py --name CNA']
[2023-04-11T16:51:03.557+0000] {subprocess.py:86} INFO - Output:
[2023-04-11T16:51:03.632+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/src/news_comments_crawlers/crawlers/_EN_CNA.py': [Errno 5] Input/output error
[2023-04-11T16:51:03.635+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-11T16:51:03.644+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-11T16:51:03.648+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_24hr_data_scrape, task_id=id_2, execution_date=20230411T164500, start_date=20230411T165103, end_date=20230411T165103
[2023-04-11T16:51:03.657+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 640 for task id_2 (Bash command failed. The command returned a non-zero exit code 2.; 5691)
[2023-04-11T16:51:03.690+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-11T16:51:03.706+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
